/**
 * Represents a Meme entity.
 * This is the unified format used for both search results and list results.
 */
export interface Meme {
  /** The unique identifier of the meme. */
  id: string;
  /** The URL of the meme image. */
  url: string;
  /**
   * The similarity score from a search query.
   * Defaults to 0 for list results (non-search).
   */
  score?: number;
  /**
   * The description of the meme generated by a VLM (Vision-Language Model).
   */
  description?: string;
  /** The category the meme belongs to. */
  category?: string;
  /** A list of tags associated with the meme. */
  tags?: string[];
  /** The width of the meme image in pixels. */
  width?: number;
  /** The height of the meme image in pixels. */
  height?: number;
  /** Structured image info returned by the backend. */
  image_info?: ImageInfo;
  /** Derived image format for UI display/download names. */
  format?: string;

  // Legacy fields for demo data compatibility
  /**
   * @deprecated Use `description` instead.
   * Legacy field for VLM description.
   */
  vlm_description?: string;
  /**
   * @deprecated Use `url` instead if possible, or keep for reference.
   * Legacy field for the original URL.
   */
  original_url?: string;
  /**
   * @deprecated
   * Legacy field for the creation timestamp.
   */
  created_at?: string;
}

/**
 * Structured image metadata returned as backend `image_info`.
 */
export interface ImageInfo {
  width?: number;
  height?: number;
  format?: number | string;
}

/**
 * Represents a search result returned from the backend.
 * This structure mirrors the `Meme` interface but often guarantees certain fields like `score`.
 */
export interface SearchResult {
  /** The unique identifier of the result. */
  id: string;
  /** The URL of the result image. */
  url: string;
  /** The similarity score of the result. */
  score: number;
  /** The description of the result. */
  description: string;
  /** The category of the result. */
  category: string;
  /** Tags associated with the result. */
  tags: string[];
  /** The width of the result image. */
  width?: number;
  /** The height of the result image. */
  height?: number;
  /** Structured image info returned by the backend. */
  image_info?: ImageInfo;
  /** Derived text-presence filter state from backend annotations. */
  text_presence?: 'unknown' | 'with_text' | 'without_text' | string;
}

/**
 * Represents the parameters for a search request.
 */
export interface SearchRequest {
  /** The search query string. */
  query: string;
  /**
   * The number of top results to return.
   * @default 10 (or whatever the backend default is)
   */
  top_k?: number;
  /** Optional category filter. */
  category?: string;
  /** Optional multi-route search profile. */
  profile?: string;
  /** Legacy optional collection key; retained for backend compatibility. */
  collection?: string;
}

/**
 * Represents the response from a search request.
 */
export interface SearchResponse {
  /** The list of search results. */
  results: SearchResult[];
  /** The total number of results found. */
  total: number;
  /** The backend profile used for this search, when applicable. */
  profile?: string;
  /** The backend collection used for legacy single-collection search. */
  collection?: string;
}

/**
 * Represents a meme category.
 * Note: The backend currently returns string arrays for categories, not objects matching this interface.
 */
export interface Category {
  /** The name of the category. */
  name: string;
  /** The count of items in this category (optional). */
  count?: number;
}

/**
 * Represents the response from a categories request.
 */
export interface CategoriesResponse {
  /** The list of available category names. */
  categories: string[];
  /** The total number of categories. */
  total: number;
}

/**
 * Represents the response from a request to list memes.
 * Uses the unified `SearchResult` format.
 */
export interface MemesListResponse {
  /** The list of meme results. */
  results: SearchResult[];
  /** The total number of memes available. */
  total: number;
  /** The limit used for pagination. */
  limit: number;
  /** The offset used for pagination. */
  offset: number;
}

/**
 * Represents aggregate system stats returned by the backend.
 */
export interface StatsResponse {
  /** Number of memes available for search and browsing. */
  total_memes: number;
  /** Number of categories currently available. */
  total_categories: number;
  /** Names of search collections exposed by the backend. */
  available_collections?: string[];
  /** Names of multi-route search profiles exposed by the backend. */
  available_profiles?: string[];
}
