// emomo wire types now live in @gen/emomo/v1/*, generated by protoc-gen-es
// from backend/proto/emomo/v1/*.proto. This file holds only the small UI
// projection used by hand-written React components — a flattened shape that
// bridges the protobuf SearchResult (with nested Meme + ImageInfo + enums)
// and the local fallback dataset (frontend/src/data/curatedMemes.ts) so that
// MemeCard / MemeModal can render either source uniformly.

import { ImageFormat, TextPresence } from '@gen/emomo/v1/types_pb';
import type { Meme as PbMeme } from '@gen/emomo/v1/meme_pb';
import type { SearchResult as PbSearchResult } from '@gen/emomo/v1/meme_pb';

/** Lowercase image format string used by UI download names and Content-Type derivations. */
export type ImageFormatSlug = 'jpg' | 'png' | 'webp' | 'unknown';

/** UI-side projection of a meme. Built either from a backend SearchResult or from local demo data. */
export interface DisplayMeme {
  /** Stable meme identifier. */
  id: string;
  /** Storage URL the UI loads / downloads. */
  url: string;
  /** Similarity score in [0, 1]; absent for non-search contexts. */
  score?: number;
  /** Joined VLM/OCR description shown in cards and modal. */
  description: string;
  /** Meme category (free-form string). */
  category?: string;
  /** Tags array — never undefined; empty when no tags. */
  tags: string[];
  /** Intrinsic image width / height in pixels. */
  width?: number;
  height?: number;
  /** Lowercase format slug for download filename + Content-Type. */
  format?: ImageFormatSlug;
  /** OCR-derived text presence label, used for filter UI affordances. */
  textPresence?: 'unknown' | 'with_text' | 'without_text';
}

/** Search-progress UI state used by App.tsx. */
export interface SearchUIState {
  isStreaming: boolean;
  /** Last seen stage (lowercase short form, used for the progress component). */
  stage:
    | 'query_expansion_start'
    | 'thinking'
    | 'query_expansion_done'
    | 'embedding'
    | 'searching'
    | 'enriching'
    | 'complete'
    | 'error';
  message: string;
  thinkingText: string;
  expandedQuery?: string;
}

/** Maps an ImageFormat enum value to a stable lowercase slug. */
export function imageFormatToSlug(format?: ImageFormat): ImageFormatSlug | undefined {
  switch (format) {
    case ImageFormat.JPEG:
      return 'jpg';
    case ImageFormat.PNG:
      return 'png';
    case ImageFormat.WEBP:
      return 'webp';
    default:
      return undefined;
  }
}

/** Maps a TextPresence enum to its stable string used by the search UI. */
export function textPresenceToSlug(p?: TextPresence): DisplayMeme['textPresence'] {
  switch (p) {
    case TextPresence.WITH_TEXT:
      return 'with_text';
    case TextPresence.WITHOUT_TEXT:
      return 'without_text';
    case TextPresence.UNKNOWN:
      return 'unknown';
    default:
      return undefined;
  }
}

/** Projects a backend Meme + optional context (score/description) into the UI shape. */
export function pbMemeToDisplay(meme: PbMeme, extras?: { score?: number; description?: string; textPresence?: TextPresence }): DisplayMeme {
  return {
    id: meme.id,
    url: meme.url,
    score: extras?.score,
    description: extras?.description ?? '',
    category: meme.category || undefined,
    tags: meme.tags ?? [],
    width: meme.imageInfo?.width || undefined,
    height: meme.imageInfo?.height || undefined,
    format: imageFormatToSlug(meme.imageInfo?.format),
    textPresence: textPresenceToSlug(extras?.textPresence),
  };
}

/** Projects a backend SearchResult (search context) into the UI shape. */
export function pbSearchResultToDisplay(result: PbSearchResult): DisplayMeme {
  if (!result.meme) {
    return {
      id: '',
      url: '',
      description: result.description ?? '',
      tags: [],
    };
  }
  return pbMemeToDisplay(result.meme, {
    score: result.score,
    description: result.description,
    textPresence: result.textPresence,
  });
}
