// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: emomo/v1/schema.proto

// Package emomo.v1 defines emomo's protobuf value schema.
//
// SCOPE:
//   This schema is intentionally limited to (a) closed enumerations whose
//   numeric value is persisted, and (b) JSON-shaped values that are stored
//   inline as columns in the relational database. It is NOT a transport or
//   wire/RPC contract — there are no top-level Meme / MemeAnnotation / MemeVector
//   messages here, because emomo's HTTP API uses Go structs + encoding/json
//   directly and does not speak protobuf on the wire.
//
//   Tables (memes, meme_annotations, meme_vectors) and their non-structured
//   columns are defined by GORM model structs in backend/internal/domain/
//   (see also backend/internal/repository/db.go for migrations). This file
//   only owns the column-level structured values listed below.
//
// Owned by this schema:
//   - enum ImageFormat   (memes.image_info.format, persisted as enum number)
//   - enum VectorType    (meme_vectors.vector_type, persisted as INTEGER)
//   - message ImageInfo  (memes.image_info JSON column)
//   - message TextLabel  (nested in MemeAnnotationLabels)
//   - message MemeAnnotationLabels (meme_annotations.labels JSON column)

package emomov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageFormat int32

const (
	ImageFormat_IMAGE_FORMAT_UNSPECIFIED ImageFormat = 0
	ImageFormat_IMAGE_FORMAT_JPEG        ImageFormat = 1
	ImageFormat_IMAGE_FORMAT_PNG         ImageFormat = 2
	ImageFormat_IMAGE_FORMAT_WEBP        ImageFormat = 3
)

// Enum value maps for ImageFormat.
var (
	ImageFormat_name = map[int32]string{
		0: "IMAGE_FORMAT_UNSPECIFIED",
		1: "IMAGE_FORMAT_JPEG",
		2: "IMAGE_FORMAT_PNG",
		3: "IMAGE_FORMAT_WEBP",
	}
	ImageFormat_value = map[string]int32{
		"IMAGE_FORMAT_UNSPECIFIED": 0,
		"IMAGE_FORMAT_JPEG":        1,
		"IMAGE_FORMAT_PNG":         2,
		"IMAGE_FORMAT_WEBP":        3,
	}
)

func (x ImageFormat) Enum() *ImageFormat {
	p := new(ImageFormat)
	*p = x
	return p
}

func (x ImageFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_emomo_v1_schema_proto_enumTypes[0].Descriptor()
}

func (ImageFormat) Type() protoreflect.EnumType {
	return &file_emomo_v1_schema_proto_enumTypes[0]
}

func (x ImageFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageFormat.Descriptor instead.
func (ImageFormat) EnumDescriptor() ([]byte, []int) {
	return file_emomo_v1_schema_proto_rawDescGZIP(), []int{0}
}

type VectorType int32

const (
	VectorType_VECTOR_TYPE_UNSPECIFIED VectorType = 0
	VectorType_VECTOR_TYPE_IMAGE       VectorType = 1
	VectorType_VECTOR_TYPE_CAPTION     VectorType = 2
)

// Enum value maps for VectorType.
var (
	VectorType_name = map[int32]string{
		0: "VECTOR_TYPE_UNSPECIFIED",
		1: "VECTOR_TYPE_IMAGE",
		2: "VECTOR_TYPE_CAPTION",
	}
	VectorType_value = map[string]int32{
		"VECTOR_TYPE_UNSPECIFIED": 0,
		"VECTOR_TYPE_IMAGE":       1,
		"VECTOR_TYPE_CAPTION":     2,
	}
)

func (x VectorType) Enum() *VectorType {
	p := new(VectorType)
	*p = x
	return p
}

func (x VectorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VectorType) Descriptor() protoreflect.EnumDescriptor {
	return file_emomo_v1_schema_proto_enumTypes[1].Descriptor()
}

func (VectorType) Type() protoreflect.EnumType {
	return &file_emomo_v1_schema_proto_enumTypes[1]
}

func (x VectorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VectorType.Descriptor instead.
func (VectorType) EnumDescriptor() ([]byte, []int) {
	return file_emomo_v1_schema_proto_rawDescGZIP(), []int{1}
}

type ImageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Format        ImageFormat            `protobuf:"varint,3,opt,name=format,proto3,enum=emomo.v1.ImageFormat" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInfo) Reset() {
	*x = ImageInfo{}
	mi := &file_emomo_v1_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInfo) ProtoMessage() {}

func (x *ImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_emomo_v1_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInfo.ProtoReflect.Descriptor instead.
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return file_emomo_v1_schema_proto_rawDescGZIP(), []int{0}
}

func (x *ImageInfo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ImageInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ImageInfo) GetFormat() ImageFormat {
	if x != nil {
		return x.Format
	}
	return ImageFormat_IMAGE_FORMAT_UNSPECIFIED
}

type TextLabel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Present       bool                   `protobuf:"varint,1,opt,name=present,proto3" json:"present,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextLabel) Reset() {
	*x = TextLabel{}
	mi := &file_emomo_v1_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextLabel) ProtoMessage() {}

func (x *TextLabel) ProtoReflect() protoreflect.Message {
	mi := &file_emomo_v1_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextLabel.ProtoReflect.Descriptor instead.
func (*TextLabel) Descriptor() ([]byte, []int) {
	return file_emomo_v1_schema_proto_rawDescGZIP(), []int{1}
}

func (x *TextLabel) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

type MemeAnnotationLabels struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          *TextLabel             `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemeAnnotationLabels) Reset() {
	*x = MemeAnnotationLabels{}
	mi := &file_emomo_v1_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemeAnnotationLabels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemeAnnotationLabels) ProtoMessage() {}

func (x *MemeAnnotationLabels) ProtoReflect() protoreflect.Message {
	mi := &file_emomo_v1_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemeAnnotationLabels.ProtoReflect.Descriptor instead.
func (*MemeAnnotationLabels) Descriptor() ([]byte, []int) {
	return file_emomo_v1_schema_proto_rawDescGZIP(), []int{2}
}

func (x *MemeAnnotationLabels) GetText() *TextLabel {
	if x != nil {
		return x.Text
	}
	return nil
}

var File_emomo_v1_schema_proto protoreflect.FileDescriptor

const file_emomo_v1_schema_proto_rawDesc = "" +
	"\n" +
	"\x15emomo/v1/schema.proto\x12\bemomo.v1\"h\n" +
	"\tImageInfo\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12-\n" +
	"\x06format\x18\x03 \x01(\x0e2\x15.emomo.v1.ImageFormatR\x06format\"%\n" +
	"\tTextLabel\x12\x18\n" +
	"\apresent\x18\x01 \x01(\bR\apresent\"?\n" +
	"\x14MemeAnnotationLabels\x12'\n" +
	"\x04text\x18\x01 \x01(\v2\x13.emomo.v1.TextLabelR\x04text*o\n" +
	"\vImageFormat\x12\x1c\n" +
	"\x18IMAGE_FORMAT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11IMAGE_FORMAT_JPEG\x10\x01\x12\x14\n" +
	"\x10IMAGE_FORMAT_PNG\x10\x02\x12\x15\n" +
	"\x11IMAGE_FORMAT_WEBP\x10\x03*Y\n" +
	"\n" +
	"VectorType\x12\x1b\n" +
	"\x17VECTOR_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11VECTOR_TYPE_IMAGE\x10\x01\x12\x17\n" +
	"\x13VECTOR_TYPE_CAPTION\x10\x02B6Z4github.com/timmy/emomo/internal/idl/emomo/v1;emomov1b\x06proto3"

var (
	file_emomo_v1_schema_proto_rawDescOnce sync.Once
	file_emomo_v1_schema_proto_rawDescData []byte
)

func file_emomo_v1_schema_proto_rawDescGZIP() []byte {
	file_emomo_v1_schema_proto_rawDescOnce.Do(func() {
		file_emomo_v1_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_emomo_v1_schema_proto_rawDesc), len(file_emomo_v1_schema_proto_rawDesc)))
	})
	return file_emomo_v1_schema_proto_rawDescData
}

var file_emomo_v1_schema_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_emomo_v1_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_emomo_v1_schema_proto_goTypes = []any{
	(ImageFormat)(0),             // 0: emomo.v1.ImageFormat
	(VectorType)(0),              // 1: emomo.v1.VectorType
	(*ImageInfo)(nil),            // 2: emomo.v1.ImageInfo
	(*TextLabel)(nil),            // 3: emomo.v1.TextLabel
	(*MemeAnnotationLabels)(nil), // 4: emomo.v1.MemeAnnotationLabels
}
var file_emomo_v1_schema_proto_depIdxs = []int32{
	0, // 0: emomo.v1.ImageInfo.format:type_name -> emomo.v1.ImageFormat
	3, // 1: emomo.v1.MemeAnnotationLabels.text:type_name -> emomo.v1.TextLabel
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_emomo_v1_schema_proto_init() }
func file_emomo_v1_schema_proto_init() {
	if File_emomo_v1_schema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_emomo_v1_schema_proto_rawDesc), len(file_emomo_v1_schema_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_emomo_v1_schema_proto_goTypes,
		DependencyIndexes: file_emomo_v1_schema_proto_depIdxs,
		EnumInfos:         file_emomo_v1_schema_proto_enumTypes,
		MessageInfos:      file_emomo_v1_schema_proto_msgTypes,
	}.Build()
	File_emomo_v1_schema_proto = out.File
	file_emomo_v1_schema_proto_goTypes = nil
	file_emomo_v1_schema_proto_depIdxs = nil
}
